---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: metrics-target-fixer
spec:
  params:
  - name: alertname
    value: "$(body.alerts[0].labels.alertname)"
  - name: namespace
    value: "$(body.alerts[0].labels.namespace)"
  - name: service
    value: "$(body.alerts[0].labels.service)"
