---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: metrics-target-fixer
spec:
  serviceAccountName: pipeline
  bindings:
  - kind: TriggerBinding
    ref: metrics-target-fixer
  interceptors:
  - params:
    - name: "filter"
      value: "body.alerts.exists(a, a.labels.alertname == 'TargetDown')"
    ref:
      kind: ClusterInterceptor
      name: cel
  template:
    ref: metrics-target-fixer
