---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: alertmanager-failure
spec:
  serviceAccountName: pipeline
  bindings:
  - kind: TriggerBinding
    ref: alertmanager-failure
  interceptors:
  - params:
    - name: "filter"
      value: "body.alerts.exists(a, a.labels.alertname == 'Watchdog')"
    ref:
      kind: ClusterInterceptor
      name: cel
  template:
    ref: alertmanager-failure
